name: Deploy Site to Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # 可选：缓存 Hugo Modules，加速并减少网络波动
      - name: Cache Hugo modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/hugo/modules
          key: ${{ runner.os }}-hugo-${{ hashFiles('**/hugo.yaml') }}
          restore-keys: ${{ runner.os }}-hugo-

      - name: Build
        run: hugo --minify

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
